version: '3.9' # Версия синтаксиса
services:
  backend:
    build: ./backend
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - main

  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - "/app/node_modules"
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - main

  
networks:
  main:
    driver: bridge